language: scala
# Trusty VM has 1.8u101
# https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-243534696
dist: trusty
sudo: false
group: beta
scala:
- 2.12.1
- 2.11.8
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm